# Generated by Django 5.0.4 on 2024-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=50, unique=True)),
                ('productName', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockQuantity', models.PositiveIntegerField(default=0)),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
